stages:
  - test
  - build
  - package
  - deploy
  - release

server unit test:
  image: maven:3.9-eclipse-temurin-17
  variables:
    TZ: 'Asia/Shanghai'
  stage: test
  needs: [ ]
  script:
    - mvn clean verify -B -s maven-settings.xml
    - mvn sonar:sonar -B -s maven-settings.xml -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST_URL -Dproject.settings=./sonar-project.properties
    - cat carbon-coverage/target/site/jacoco-aggregate/index.html
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    paths:
      - carbon-coverage/target/site/jacoco-aggregate
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"
        - "**/target/failsafe-reports/TEST-*.xml"

server build:
  image: maven:3.9-eclipse-temurin-17
  stage: build
  needs: [ ]
  script:
    - mvn clean package -DskipTests=true -s maven-settings.xml

deploy:
  stage: deploy
  needs: [ ]
  script:
    - mvn clean deploy -DskipTests=true -B -s maven-settings.xml
  only:
    - main

release:
  stage: release
  needs: [ ]
  before_script:
    - mkdir ~/.ssh
    - cp $DEPLOY_PRIVATE_KEY ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H gitlab.wisefin.tech > ~/.ssh/known_hosts
    - git config user.email "ci@wisefin.tech"
    - git config user.name "Gitlab CI"
    - git checkout -B "$CI_COMMIT_REF_NAME"
  when: manual
  only:
    - main
  script:
    - mvn release:prepare release:perform -DskipTests=true -DscmCommentPrefix="[skip ci]" -B -s maven-settings.xml

